---
- name: Check for existing Satellite deployment before continuing
  hosts: all
  roles:
    - check-for-existing-satellite

- name: Configure OS
  hosts: all
  become: yes
  roles:
    - hostname
    - firewall
    - etc-hosts
    - register

- name: Install and Configure Satellite
  hosts: all
  become: yes
  roles:
    - install-satellite
    - manifest
    - sync-plan
    - lazy-sync
    - lifecycle-environments
    - product-repo-RHEL7
    - product-repo-EPEL7
    - ccv-RHEL7-EPEL7
    - product-repo-EAP7
    - ccv-RHEL7-EAP7
    - activation-keys
    - provision-libvirt
#    - ansible-tower-sync-prep
