---
- name: Check to see if the system is subscribed
  command: subscription-manager status
  register: result
  ignore_errors: True

- name: Register to RHN and attach Satellite SKU through Activation Key
  redhat_subscription:
    state: present
    activationkey: "{{ satellite_activation_key }}"
    org_id: "{{ rhn_org_id }}"
  when: not satellite_is_installed and result is failed
  tags: register

- name: Disable All Repositories
  command: subscription-manager repos --disable "*"
  when: not satellite_is_installed and result is failed
  tags: register

- name: Enable Satellite repositories
  command: /usr/sbin/subscription-manager repos --enable="{{item}}"
  with_items: "{{ satellite_repos }}"
  when: not satellite_is_installed and result is failed
  tags: register
